services:
  - type: web
    name: telegram-moderator-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false # Render dashboard mein manual enter karna hoga
      - key: OWNER_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 10000
